### ISSUE TITLE
Create filtering interface for map

### ISSUE THREAD

**Issue by james-minton** [Hyperobjekt/bil-map#27]
Create UI to allow filtering of map based on the following criteria:

- implementation status (column P in the client's data)
  - active
  - concluded
 - number of participants
   - < 1,000 
   - 1,000-9,999 
   - 10,000-99,999 
   - 100,000-999,999 
   - \> 1,000,000
- type of funding (column S)
  - public
  - private 
- Type of targeting (filter applies if column V contains the following words):
  - Geographic
  - means-testing
  - demographic
  - program/service participation
  - none

## Behavior

- When filters are applied, only dots on the map matching the filter(s) will be shown. 
- Show number of results (TODO: think through UI ramifications and add to design)
- _Within_ categories (e.g. "implementation status"), filtering is additive/inclusionary: so clicking both "active" and "concluded" would show all pilots matching "active" OR "concluded."
- _Across_ categories, filtering becomes subtractive, so clicking "type of funding: public" and "implementation status: active" would show only pilots matching "public" AND "active"
- "Clear filters" resets the map to its original state.
- Hovering the (?) icon shows a tooltip explaining the category 
  - client dependency: supply tooltip copy

## Implementation

[Refer to mockups here](https://www.figma.com/file/YlxU0ZV5pVgEXHNsHsR80w/BIL-MAP-mockups?node-id=560%3A3).

- [ ] Implement in the app

## For reference

- See [readme](https://github.com/Hyperobjekt/bil-map#readme) to understand how data is loaded into this app.

**Comment by reefdog** [comment]
@james-minton I just realized filtering by participant count is complicated by the data in that column, which sometimes contains difficult-to-parse quantities like "200 receiving bi-weekly payment, 200 receiving bi-annual payment" or even "800+". I hesitate to blindly run some regex on it to extract what I hope is the right value. Do you think we could either conform this column to a "numbers only" format, or add a new "numbers only" version of the data? (I don't know what downstream effects adding a column will have, e.g. if the data mapping is positional.)

Couple of UX questions:

1. **Do filter states need to be saved to / reconstructed from the URL query params (like selected experiments are)?**
2. **What should happen to selected experiments as the filter is changed?** Easiest answer is "any filter change clears/closes selected experiments. If we keep them selected, should they at least be deselected if they no longer match the current filter conditions?

**Comment by reefdog** [comment]
@james-minton I wanted to draw attention to some data sanitation issues that cause strange filter results. These are evident when you select all options for a given filter category (i.e., select all "Number of Participants" options) and see that the "Display `n` experiment sites" count in the top right doesn't add up to the expected 128.

- Two rows don't have usable `participant` values, so the `participant_number` column is blank, thus they don't qualify for any of the options. (We can't fall back on "<1000" since we don't actually know that's accurate.)
- Seven rows have incorrect or missing `funding` values. Expected values are Public, Private, or Public/Private (or Private/Public); it seems some rows have a different column's value here, e.g. row 59 (EID `lugi`) seems to have the `unit` value of "Individuals" in the `funding` column, and the `funding` value of "Public/Private" in column S.
- Values for `targeting` are not completely consistent, but I believe I've been able to handle all variations. E.g. "Means-testing" matches even when the row says "means testing" (omitting the hyphen). I also mapped "None" to three different values: "None", "No criteria", and a blank cell.

The only column that I think needs manual correction are the `funding` values, the others are just an FYI (and sanity check).
