### ISSUE TITLE
"Only 3 experiments ..." hint appears in error

### ISSUE THREAD

**Issue by james-minton** [Hyperobjekt/bil-map#7]
Steps to reproduce:

- Attempt to select 4 experiments.
- Dismiss all selected experiments.
- Click on another experiment -- popup appears briefly, in error

System/browser: Mac/Chrome

**Comment by hoshmn** [comment]
Yeah, saw this too. Fixed by
ea5fca49412db5cea4d16c15b1557245f52159f7
ef91c33c0067c403b2a8653e2869c5071856770c
Also fixed a bug with the Selection user-hint so that it now animates in every time (until it's been "dismissed" by user selecting >1 points) rather than appearing awkwardly above the card as it slides up (mobile view specific).
2cfae17b65764a2f25eef0ed591e3f5aa67cc0cc
